const personnels = [
  {
    id: 1,
    name: "Joseph Ukoh",
    priv: "Elder",
    CO: true,
    SO: false,
    SEC: false,
  },
  {
    id: 2,
    name: "Nse Ekeh",
    priv: "Elder",
    CO: false,
    SO: true,
    SEC: false,
  },
  {
    id: 3,
    name: "Joseph Udonde",
    priv: "Elder",
    CO: false,
    SO: false,
    SEC: true,
  },
  {
    id: 4,
    name: "Joseph Udobang",
    priv: "Elder",
    CO: false,
    SO: false,
    SEC: false,
  },
  {
    id: 5,
    name: "Idopise James",
    priv: "Elder",
    CO: false,
    SO: false,
    SEC: false,
  },
  {
    id: 6,
    name: "Iniobong John",
    priv: "Elder",
    CO: false,
    SO: false,
    SEC: false,
  },
  {
    id: 7,
    name: "Matthias William",
    priv: "Elder",
    CO: false,
    SO: false,
    SEC: false,
  },
  {
    id: 8,
    name: "Nkereuwem Etim",
    priv: "Elder",
    CO: false,
    SO: false,
    SEC: false,
  },
  {
    id: 9,
    name: "Emmanuel Nyah",
    priv: "Elder",
    CO: false,
    SO: false,
    SEC: false,
  },
  {
    id: 10,
    name: "Okon Umofia",
    priv: "Elder",
    CO: false,
    SO: false,
    SEC: false,
  },
  {
    id: 11,
    name: "Michael Iyamah",
    priv: "Elder",
    CO: false,
    SO: false,
    SEC: false,
  },
  {
    id: 12,
    name: "Ubong Wilson",
    priv: "Elder",
    CO: false,
    SO: false,
    SEC: false,
  },
  {
    id: 13,
    name: "Effiong Ibok",
    priv: "Elder",
    CO: false,
    SO: false,
    SEC: false,
  },
  {
    id: 14,
    name: "Michael Uko",
    priv: "MS",
    CO: false,
    SO: false,
    SEC: false,
  },
  {
    id: 15,
    name: "Michael Essien",
    priv: "MS",
    CO: false,
    SO: false,
    SEC: false,
  },
  {
    id: 16,
    name: "Michael Effiong",
    priv: "MS",
    CO: false,
    SO: false,
    SEC: false,
  },
  {
    id: 17,
    name: "Godwin Etuk",
    priv: "MS",
    CO: false,
    SO: false,
    SEC: false,
  },

  {
    id: 18,
    name: "Innocent William",
    priv: "MS",
    CO: false,
    SO: false,
    SEC: false,
  },
  {
    id: 19,
    name: "Edem Edet",
    priv: "MS",
    CO: false,
    SO: false,
    SEC: false,
  },
  {
    id: 20,
    name: "Daniel John",
    priv: "MS",
    CO: false,
    SO: false,
    SEC: false,
  },
  {
    id: 21,
    name: "Kuyik Eyamba",
    priv: "MS",
    CO: false,
    SO: false,
    SEC: false,
  },
  {
    id: 22,
    name: "Jahaziel Uko",
    priv: "MS",
    CO: false,
    SO: false,
    SEC: false,
  },
];

const assignments = [
  { id: 0, name: "Chairman" },
  { id: 1, name: "Opening Prayer" },
  { id: 2, name: "Treasure From God's Word" },
  { id: 3, name: "Spiritual GeMS" },
  { id: 4, name: "Apply Yourself to Ministry - 1" },
  { id: 5, name: "Apply Yourself to Ministry - 2" },
  { id: 6, name: "Living As Christians - 1" },
  { id: 7, name: "Living As Christians - 2" },
  { id: 8, name: "Congregation Bible Study" },
  { id: 9, name: "Closing Prayer" },
];

export { personnels, assignments };
